### PR TITLE
A suggestion only

### PR DESCRIPTION
**Pull request by 17Halbe**
Changed the Variable name again as mentioned on gitter! :joy: 
And made the default recipient of the report the `POSTMASTER_ADDRESS`.
Also tried to do the documentation.

Hope that's to your liking, otherwise just discard it.

### CODE REVIEW

**Comment by akmet** [comment]
Wrong branch :joy:
Seems good

**Comment by 17Halbe** [comment]
AArghh!!!

**Comment by 17Halbe** [comment]
I just realized, you merged the last PR already, that's why I can't submit one for the old branch. you would have to create a new one for me.. Or is there another way?

**Comment by akmet** [comment]
Have a look at it later, currently at an Diskothek...

**Comment by 17Halbe** [comment]
:joy: 
:+1: 
I was sitting in a train, horrible trip, no sleep, no internet..

**Pull request closed without merging**
